allowBuilds:
  esbuild: set this to true or false
  protobufjs: set this to true or false
  redis-memory-server: set this to true or false
minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.6'
  - '@tanstack/router-core@1.171.4'
  - '@tanstack/router-generator@1.167.8'
  - '@tanstack/router-plugin@1.168.9'
  - '@tanstack/router-utils@1.162.1'
  - '@tanstack/router-vite-plugin@1.167.9'
